name: Build and Test with Maven

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'development'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:

          java-version: '17'
          distribution: 'adopt'


      - name:  Generar settings.xml for Maven Builds
        uses:  whelk-io/maven-settings-xml-action@v21
        with:
          repositories: '[{ "id": "github", "url": "https://maven.pkg.github.com/otordzdl/infinite-growth-automation-core" }]'
          servers: '[{ "id": "github", "username": "${{ secrets.MAVEN_GITHUB_USERNAME }}", "password": "${{ secrets.MAVEN_GITHUB_TOKEN }}" }]'

      - name: Revisar pom
        run: cat /home/runner/.m2/settings.xml
      
      - name: Run tests
        run: mvn test

      - name: Upload extent report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: reporte-extent.html
          retention-days: 20
        env:
          TOKEN: ${{ secrets.MAVEN_GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ secrets.MAVEN_GITHUB_USERNAME }}
          DEVICE_FARM_API_KEY: ${{ secrets.DEVICE_FARM_API_KEY }}
          DEVICE_FARM_USER: ${{ secrets.DEVICE_FARM_USER }}

