name: Build and Test with Maven

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'development'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '20.0.2+9'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install --file pom.xml

      - name: Run tests
        run: mvn test
        env:
          GITHUB_TOKEN: ${{ secrets.MAVEN_GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ secrets.MAVEN_GITHUB_USERNAME }}