name: Build and Test with Maven

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'development'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '20.0.2+9'
          distribution: 'adopt'
         
 #     - name: maven-settings
  #      uses: s4u/maven-settings-action@v2
   #     with:
    #     servers: |
     #      [{
      #        "id": "github",
       #       "username": "${{ secrets.GITHUB_USERNAME }}",
        #      "password": "${{ secrets.GITHUB_TOKEN }}",
         #     "url": "https://maven.pkg.github.com/otordzdl/infinite-growth-automation-core"            
          #  }]

      - name:  Generate settings.xml for Maven Builds
        uses:  whelk-io/maven-settings-xml-action@v21
        with:
          servers: '[{"id": "github", "username": "${{ secrets.GITHUB_USERNAME }}", "password": "${{ secrets.GITHUB_TOKEN }}"}]'
          repositories: '[{"id": "github", "url": "https://maven.pkg.github.com/otordzdl/infinite-growth-automation-core"}]'
          
         


      - name: revisar m2
        run: cat  /home/runner/.m2/settings.xml


      - name: Run tests
        run: mvn test
        env:
          GITHUB_TOKEN: ${{ secrets.MAVEN_GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ secrets.MAVEN_GITHUB_USERNAME }}
